const { z } = require('zod');
const CATEGORY=['technical','behavioural','system-design','company-fit'];
const KitSchema=z.object({source:z.object({company:z.string(),company_url:z.string(),role:z.string(),location:z.string(),jd_chars:z.number().int(),researched_at:z.string(),pages_used:z.array(z.string())}),company_brief:z.object({summary:z.string(),what_they_do:z.string(),sources:z.array(z.string())}),role:z.object({title:z.string(),seniority:z.string(),responsibilities:z.array(z.string()),requirements:z.array(z.object({id:z.string(),text:z.string(),kind:z.enum(['technical','behavioural','domain']),priority:z.enum(['must','nice'])}))}),questions:z.array(z.object({id:z.string(),requirement_ids:z.array(z.string()),category:z.enum(CATEGORY),prompt:z.string(),answer_outline:z.string(),difficulty:z.number().int().min(1).max(3)}).passthrough()),flashcards:z.array(z.object({id:z.string(),front:z.string(),back:z.string(),requirement_ids:z.array(z.string())}).passthrough()),schedule:z.object({days_available:z.number().int().min(1).max(60),days:z.array(z.object({day:z.number().int(),focus:z.string(),question_ids:z.array(z.string()),minutes:z.number().int()}))}),coverage:z.object({uncovered_requirement_ids:z.array(z.string()),passes:z.number().int()})});
function validateKit(kit){const parsed=KitSchema.safeParse(kit);if(!parsed.success)return {ok:false,error:parsed.error.flatten()};const k=parsed.data,requirementIds=new Set(k.role.requirements.map(r=>r.id)),questionIds=new Set(k.questions.map(q=>q.id)),flashcardIds=new Set(k.flashcards.map(f=>f.id));if(requirementIds.size!==k.role.requirements.length||questionIds.size!==k.questions.length||flashcardIds.size!==k.flashcards.length)return {ok:false,error:'Requirement, question, and flashcard IDs must be unique'};if(k.questions.some(q=>q.requirement_ids.some(id=>!requirementIds.has(id)))||k.flashcards.some(f=>f.requirement_ids.some(id=>!requirementIds.has(id))))return {ok:false,error:'A question or flashcard references an unknown requirement'};if(k.schedule.days.length!==k.schedule.days_available||k.schedule.days.some((d,index)=>d.day!==index+1||d.minutes<0||d.question_ids.some(id=>!questionIds.has(id))))return {ok:false,error:'Invalid schedule references or day count'};const expectedUncovered=coverage(k.role.requirements,k.questions);if(expectedUncovered.length!==k.coverage.uncovered_requirement_ids.length||expectedUncovered.some(id=>!k.coverage.uncovered_requirement_ids.includes(id)))return {ok:false,error:'Coverage does not match the current questions'};return {ok:true};}
function clean(s){return s.replace(/\s+/g,' ').trim()}
function extractRequirements(jd){const lines=jd.split(/\n|(?<=[.!?])\s+/).map(clean).filter(x=>x.length>12);const key=/(required|requirements|must|need to|you have|experience|proficien|expert|knowledge|skills?|bonus|nice to have|preferred|responsib|mentor|lead|design|build|develop|collaborat)/i;let found=lines.filter(x=>key.test(x)).slice(0,12);if(!found.length)found=lines.filter(x=>x.length>20).slice(0,3);return found.map((text,i)=>({id:'r'+(i+1),text,kind:/(mentor|collaborat|lead|communicat|stakeholder)/i.test(text)?'behavioural':/(industry|domain|product|customer|compliance)/i.test(text)?'domain':'technical',priority:/(bonus|nice to have|preferred|plus|ideally)/i.test(text)?'nice':'must'}));}
function titleOf(jd){return (jd.match(/(?:senior|junior|staff|lead|principal)?\s*[A-Z][A-Za-z/ -]{2,}(?:engineer|developer|designer|manager|analyst)/i)||['Interview role'])[0].trim()}
function categoryFor(r){return r.kind==='behavioural'?'behavioural':/(architect|system|scal|reliab|api|design)/i.test(r.text)?'system-design':'technical'}
function question(r,n){const cat=categoryFor(r);return {id:'q'+n,requirement_ids:[r.id],category:cat,prompt:cat==='behavioural'?`Tell me about a time you demonstrated: ${r.text}`:`How would you apply ${r.text} in this role?`,answer_outline:'Use a specific example; explain your decision-making, trade-offs, measurable outcome, and what you learned.',difficulty:r.priority==='must'?2:1,state:'generated'};}
function coverage(requirements,questions){const covered=new Set(questions.flatMap(q=>q.requirement_ids));return requirements.filter(r=>r.priority==='must'&&!covered.has(r.id)).map(r=>r.id)}
function schedule(requirements,questions,days){const allocation=Array.from({length:days},(_,i)=>({day:i+1,focus:i===0?'Highest-priority foundations':'Targeted practice',question_ids:[],minutes:0}));const priority=r=>r.priority==='must'?0:1;const reqs=[...requirements].sort((a,b)=>priority(a)-priority(b));for(const requirement of reqs){const q=questions.find(item=>item.requirement_ids.includes(requirement.id));if(!q)continue;const earliest=priority(requirement)===0?Math.max(1,Math.ceil(days*.7)):days;const candidates=allocation.slice(0,earliest);const target=candidates.reduce((least,current)=>current.question_ids.length<least.question_ids.length?current:least,candidates[0]);target.question_ids.push(q.id)}for(const day of allocation){day.minutes=Math.max(30,Math.round((day.question_ids.length?day.question_ids.length*25:20)/5)*5);if(day.question_ids.length){const first=questions.find(q=>q.id===day.question_ids[0]);day.focus=first.category==='system-design'?'Architecture & trade-offs':first.category==='behavioural'?'Leadership & collaboration':first.category==='technical'?'Technical foundations':'Company preparation';}}return {days_available:days,days:allocation};}
module.exports={validateKit,extractRequirements,question,coverage,schedule,titleOf};
