const dns=require('dns').promises, {URL}=require('url');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function safeUrl(raw,{allowPrivate=process.env.NODE_ENV!=='production'}={}){let u;try{u=new URL(raw)}catch{throw Object.assign(new Error('Company URL is invalid.'),{code:'INVALID_URL'})}if(!['http:','https:'].includes(u.protocol))throw Object.assign(new Error('Only HTTP(S) URLs are allowed.'),{code:'INVALID_URL'});if(!allowPrivate){const addresses=await dns.lookup(u.hostname,{all:true});if(addresses.some(a=>/^(127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|::1|fc|fd)/i.test(a.address)))throw Object.assign(new Error('Private network targets are not allowed.'),{code:'UNSAFE_URL'})}return u}
async function fetchPage(url){for(let attempt=0;attempt<3;attempt++){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'TraoPrepBot/1.0 (+research; respectful crawl)'}});clearTimeout(t);if(!r.ok)throw new Error('HTTP '+r.status);const type=r.headers.get('content-type')||'';if(!/text\/(html|plain)/i.test(type))throw new Error('Unsupported content type');const text=(await r.text()).slice(0,500000);return {url:r.url,html:text}}catch(e){if(attempt===2)throw e;await delay(350*(attempt+1))}}}
function text(html){return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,12000)}
function links(html,base){const out=[];for(const m of html.matchAll(/<a[^>]+href=["']([^"'#]+)["']/gi)){try{const u=new URL(m[1],base);if(u.origin===new URL(base).origin)out.push(u.href)}catch{}}return [...new Set(out)].sort((a,b)=>Number(/career|job|hiring|about|team|culture|interview/i.test(b))-Number(/career|job|hiring|about|team|culture|interview/i.test(a))).slice(0,6)}
function robotsAllows(value,path){let applies=false;for(const line of value.split(/\r?\n/)){const [key,...parts]=line.split(':');const v=parts.join(':').trim();if(key.trim().toLowerCase()==='user-agent')applies=v==='*'||/traoprepbot/i.test(v);if(applies&&key.trim().toLowerCase()==='disallow'&&v&&path.startsWith(v))return false}return true}
async function publicDiscussion(company,warnings){try{const result=await fetchPage('https://html.duckduckgo.com/html/?q='+encodeURIComponent(company+' interview process'));const urls=[...result.html.matchAll(/result__a[^>]+href=["']([^"']+)/gi)].map(m=>m[1]).filter(u=>/^https?:/.test(u)&&!u.includes('duckduckgo.com')).slice(0,3);if(!urls.length)warnings.push('No public interview-process discussion was found.');return urls}catch{warnings.push('Public interview-process search was unavailable.');return []}}
async function research(companyUrl){const sources=[],warnings=[];let company='company';try{const url=await safeUrl(companyUrl);company=url.hostname.replace(/^www\./,'');const home=await fetchPage(url);sources.push({url:home.url,content:text(home.html)});let crawl=true;try{const robots=await fetchPage(new URL('/robots.txt',home.url));crawl=robotsAllows(robots.html,new URL(home.url).pathname)}catch{warnings.push('robots.txt could not be retrieved; crawled cautiously.')}if(crawl){for(const link of links(home.html,home.url)){await delay(150);try{const p=await fetchPage(link);sources.push({url:p.url,content:text(p.html)})}catch{warnings.push('Skipped an unavailable company page.')}}}else warnings.push('robots.txt disallowed additional crawling.')}catch(e){warnings.push('Company research unavailable: '+e.message)}const joined=sources.map(s=>s.content).join(' ').slice(0,18000),discussionSources=await publicDiscussion(company,warnings);return {sources,warnings,discussionSources,summary:joined?cleanSummary(joined):'No company information could be retrieved. This kit is based on the job description only.',what:joined?cleanSummary(joined.slice(300)): 'Company research was unavailable; verify company context directly before the interview.'}}
function cleanSummary(s){return s.slice(0,700).replace(/\s+/g,' ').trim()}
module.exports={research,safeUrl,robotsAllows};
